services:
  - type: web
    name: superset-maritime
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      pip install psycopg2-binary &&
      pip install apache-superset
    startCommand: >
      source .venv/bin/activate && ./setup.sh && .venv/bin/superset run -h 0.0.0.0 -p 8088
    envVars:
      - key: SUPERSET_CONFIG_PATH
        value: /opt/render/project/src/superset_config.py
      - key: FLASK_APP
        value: superset.app:create_app
