services:
  - type: web
    name: superset-maritime
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      pip install psycopg2-binary &&
      pip install apache-superset
    startCommand: >
      ./setup.sh && superset run -p 8088 --host 0.0.0.0 --with-threads --reload --debugger
    envVars:
      - key: SUPERSET_CONFIG_PATH
        value: /opt/render/project/src/superset_config.py
